### **Purpose:** Leakage-Safe Feature Engineering

This step creates rolling statistics, lag features, and short-term trend proxies while grouping by `season_year` to prevent information leakage across yearly July–October seasonal gaps.

In [400]:
# These columns were removed based on EDA findings
columns_to_drop = [
    "sst_cameroon_fraction_of_sea_ice_covered_ocean",   # constant value
    "sst_indian_ocean_fraction_of_sea_ice_covered_ocean",  # constant value
    "sst_cameroon_mean_temperature_kelvin",  # redundant with Celsius column
    "sst_indian_ocean_mean_temperature_kelvin",  # redundant with Celsius column
    "surface_pressure"  # almost identical to sea_level_pressure
]

In [401]:
train_clean_df = train_merged.drop(columns=columns_to_drop, errors="ignore")
test_clean_df = test_merged.drop(columns=columns_to_drop, errors="ignore")

In [402]:
print("Train shape", train_clean_df.shape)
print("Test shape", test_clean_df.shape)

print("\nRemaining columns:")
print(train_clean_df.columns.tolist())

Train shape (2214, 16)
Test shape (738, 15)

Remaining columns:
['date', '5cm_soil_moist', 'mean_dew_point_temp', 'max_temp', 'sea_level_pressure', 'sst_cameroon_mean_temperature_deg_c', 'sst_cameroon_mean_temperature_uncertainty', 'sst_indian_ocean_mean_temperature_deg_c', 'sst_indian_ocean_mean_temperature_uncertainty', 'potential_water_deficit', '2m_temp', 'u10', 'vapor_pressure_deficit', 'dryspell_warn_7d', 'year', 'month']

In [403]:
print("Train shape", train_merged.shape)
print("Test shape", test_merged.shape)

print("\nRemaining columns:")
print(train_merged.columns.tolist())

Train shape (2214, 21)
Test shape (738, 20)

Remaining columns:
['date', '5cm_soil_moist', 'mean_dew_point_temp', 'max_temp', 'sea_level_pressure', 'sst_cameroon_mean_temperature_kelvin', 'sst_cameroon_mean_temperature_deg_c', 'sst_cameroon_mean_temperature_uncertainty', 'sst_cameroon_fraction_of_sea_ice_covered_ocean', 'sst_indian_ocean_mean_temperature_kelvin', 'sst_indian_ocean_mean_temperature_deg_c', 'sst_indian_ocean_mean_temperature_uncertainty', 'sst_indian_ocean_fraction_of_sea_ice_covered_ocean', 'potential_water_deficit', 'surface_pressure', '2m_temp', 'u10', 'vapor_pressure_deficit', 'dryspell_warn_7d', 'year', 'month']

In [404]:
print("\nMissing values in train:")
print(train_clean_df.isna().sum().sort_values(ascending=False).head())

print("\nMissing values in test:")
print(test_clean_df.isna().sum().sort_values(ascending=False).head())

Missing values in train:
date                   0
5cm_soil_moist         0
mean_dew_point_temp    0
max_temp               0
sea_level_pressure     0
dtype: int64

Missing values in test:
sst_cameroon_mean_temperature_deg_c              123
sst_cameroon_mean_temperature_uncertainty        123
sst_indian_ocean_mean_temperature_deg_c          123
sst_indian_ocean_mean_temperature_uncertainty    123
mean_dew_point_temp                                1
dtype: int64

In [405]:
print("=== TEST DATA MISSINGNESS ===")
# % missing per column
missing_pct = test_merged.isna().mean() * 100
missing_cols = missing_pct[missing_pct > 0].sort_values(ascending=False)

# Rows with ANY missing data
rows_with_missing = test_merged.isna().any(axis=1).sum()
pct_rows_missing = (rows_with_missing / len(test_merged)) * 100

if len(missing_cols) == 0:
    print("Columns with missing data: None! 100% complete.")
else:
    print(f"Columns with missing data:\n{missing_cols}")
print(f"Rows with at least one missing value: {rows_with_missing} ({pct_rows_missing:.2f}%)\n")

=== TEST DATA MISSINGNESS ===
Columns with missing data:
sst_cameroon_mean_temperature_kelvin                  16.67
sst_cameroon_mean_temperature_deg_c                   16.67
sst_cameroon_mean_temperature_uncertainty             16.67
sst_cameroon_fraction_of_sea_ice_covered_ocean        16.67
sst_indian_ocean_mean_temperature_kelvin              16.67
sst_indian_ocean_mean_temperature_deg_c               16.67
sst_indian_ocean_mean_temperature_uncertainty         16.67
sst_indian_ocean_fraction_of_sea_ice_covered_ocean    16.67
mean_dew_point_temp                                    0.14
max_temp                                               0.14
sea_level_pressure                                     0.14
potential_water_deficit                                0.14
surface_pressure                                       0.14
2m_temp                                                0.14
dtype: float64
Rows with at least one missing value: 124 (16.80%)

In [406]:
print("=== TEST DATA MISSINGNESS ===")
# % missing per column
missing_pct = test_clean_df.isna().mean() * 100
missing_cols = missing_pct[missing_pct > 0].sort_values(ascending=False)

# Rows with ANY missing data
rows_with_missing = test_clean_df.isna().any(axis=1).sum()
pct_rows_missing = (rows_with_missing / len(test_clean_df)) * 100

if len(missing_cols) == 0:
    print("Columns with missing data: None! 100% complete.")
else:
    print(f"Columns with missing data:\n{missing_cols}")
print(f"Rows with at least one missing value: {rows_with_missing} ({pct_rows_missing:.2f}%)\n")

=== TEST DATA MISSINGNESS ===
Columns with missing data:
sst_cameroon_mean_temperature_deg_c              16.67
sst_cameroon_mean_temperature_uncertainty        16.67
sst_indian_ocean_mean_temperature_deg_c          16.67
sst_indian_ocean_mean_temperature_uncertainty    16.67
mean_dew_point_temp                               0.14
max_temp                                          0.14
sea_level_pressure                                0.14
potential_water_deficit                           0.14
2m_temp                                           0.14
dtype: float64
Rows with at least one missing value: 124 (16.80%)

In [407]:
train_clean_df.to_csv(processed_dir / "train_merged_clean.csv", index=False)
test_clean_df.to_csv(processed_dir / "test_merged_clean.csv", index=False)
print("Saved to:", processed_dir / "train_merged_clean.csv", "and", processed_dir / "test_merged_clean.csv")

Saved to: ../data/processed/train_merged_clean.csv and ../data/processed/test_merged_clean.csv

In [408]:
# We need to group by the calendar year so rolling windows and lags
# do not leak across the Jul-Oct gap into the next year.
train_clean_df["season_year"]= train_clean_df["date"].dt.year
test_clean_df["season_year"]= test_clean_df["date"].dt.year

In [409]:
def fill_missing_by_season(df, cols):
    df = df.sort_values(["season_year", "date"]).copy()
    df[cols] = df.groupby("season_year")[cols].ffill().bfill()
    return df

feature_cols = [c for c in train_clean_df.columns if c not in ["date", target_col, "season_year"]]
train_clean_df = fill_missing_by_season(train_clean_df, feature_cols)
test_clean_df  = fill_missing_by_season(test_clean_df, feature_cols)

In [410]:
print("=== TEST DATA MISSINGNESS ===")
# % missing per column
missing_pct = test_clean_df.isna().mean() * 100
missing_cols = missing_pct[missing_pct > 0].sort_values(ascending=False)

# Rows with ANY missing data
rows_with_missing = test_clean_df.isna().any(axis=1).sum()
pct_rows_missing = (rows_with_missing / len(test_clean_df)) * 100

if len(missing_cols) == 0:
    print("Columns with missing data: None! 100% complete.")
else:
    print(f"Columns with missing data:\n{missing_cols}")
print(f"Rows with at least one missing value: {rows_with_missing} ({pct_rows_missing:.2f}%)\n")

=== TEST DATA MISSINGNESS ===
Columns with missing data:
sst_cameroon_mean_temperature_deg_c              16.67
sst_cameroon_mean_temperature_uncertainty        16.67
sst_indian_ocean_mean_temperature_deg_c          16.67
sst_indian_ocean_mean_temperature_uncertainty    16.67
dtype: float64
Rows with at least one missing value: 123 (16.67%)

In [411]:
train_clean_df.head(10)

,date,5cm_soil_moist,mean_dew_point_temp,max_temp,sea_level_pressure,sst_cameroon_mean_temperature_deg_c,sst_cameroon_mean_temperature_uncertainty,sst_indian_ocean_mean_temperature_deg_c,sst_indian_ocean_mean_temperature_uncertainty,potential_water_deficit,2m_temp,u10,vapor_pressure_deficit,dryspell_warn_7d,year,month,season_year
0,2002-07-01,0.14,16.31,40.13,101.01,26.06,0.19,28.84,0.12,-4.61,32.73,0.76,5.45,0,2002,7,2002
1,2002-07-02,0.14,16.77,41.36,100.81,26.10,0.19,28.85,0.12,-2.92,33.37,0.68,5.52,0,2002,7,2002
2,2002-07-03,0.14,19.72,38.05,100.97,26.11,0.20,28.82,0.12,7.59,31.57,1.41,4.23,0,2002,7,2002
3,2002-07-04,0.14,18.50,39.51,100.94,26.14,0.23,28.79,0.12,-2.29,32.59,1.49,4.68,0,2002,7,2002
4,2002-07-05,0.14,17.68,40.47,100.86,26.29,0.21,28.78,0.12,-2.87,33.59,1.07,5.15,0,2002,7,2002
5,2002-07-06,0.14,16.01,39.39,100.80,26.19,0.21,28.74,0.12,-4.20,33.54,1.51,5.00,0,2002,7,2002
6,2002-07-07,0.13,17.04,39.07,100.77,26.13,0.20,28.63,0.13,-2.75,32.71,2.27,4.65,0,2002,7,2002
7,2002-07-08,0.13,16.27,38.14,100.86,26.03,0.21,28.55,0.12,6.13,32.13,0.97,4.58,0,2002,7,2002
8,2002-07-09,0.16,16.65,37.88,101.03,25.80,0.20,28.55,0.13,-3.01,31.17,0.73,4.73,0,2002,7,2002
9,2002-07-10,0.18,18.00,36.04,101.02,25.67,0.21,28.55,0.13,-2.68,30.29,0.97,4.07,0,2002,7,2002

In [412]:
test_clean_df.head()

,date,5cm_soil_moist,mean_dew_point_temp,max_temp,sea_level_pressure,sst_cameroon_mean_temperature_deg_c,sst_cameroon_mean_temperature_uncertainty,sst_indian_ocean_mean_temperature_deg_c,sst_indian_ocean_mean_temperature_uncertainty,potential_water_deficit,2m_temp,u10,vapor_pressure_deficit,year,month,season_year
0,2020-07-01,0.25,16.26,39.03,100.67,25.38,0.24,30.06,0.12,-4.10,32.32,3.13,4.96,2020,7,2020
1,2020-07-02,0.23,18.46,36.96,100.79,25.45,0.23,30.09,0.12,-3.35,31.19,3.37,4.15,2020,7,2020
2,2020-07-03,0.22,16.23,37.11,100.84,25.49,0.21,30.07,0.12,-4.79,30.94,1.36,4.56,2020,7,2020
3,2020-07-04,0.21,16.36,39.22,100.84,25.73,0.22,30.03,0.12,-1.23,31.98,1.60,5.08,2020,7,2020
4,2020-07-05,0.21,16.59,37.46,100.68,25.92,0.23,29.95,0.12,-3.73,31.39,1.56,4.23,2020,7,2020

In [413]:
# We keep only numeric columns for feature engineering.
# We exclude:
# - date: used only for ordering/splitting
# - target: label, never used as input
# - season_year: grouping helper, not a real predictor

exclude_cols =["date", target_col, "season_year"]

numeric_cols = train_clean_df.select_dtypes(include=[np.number]).columns.tolist()
base_features = [col for col in numeric_cols if col not in exclude_cols + ["year", "month"]]

print("Number of base numeric features:", len(base_features))
print(base_features)

Number of base numeric features: 12
['5cm_soil_moist', 'mean_dew_point_temp', 'max_temp', 'sea_level_pressure', 'sst_cameroon_mean_temperature_deg_c', 'sst_cameroon_mean_temperature_uncertainty', 'sst_indian_ocean_mean_temperature_deg_c', 'sst_indian_ocean_mean_temperature_uncertainty', 'potential_water_deficit', '2m_temp', 'u10', 'vapor_pressure_deficit']

In [414]:
rolling_windows = [7, 14, 30]

def add_rolling_features(df, feature_cols, windows):
    df = df.copy()
    for col in feature_cols:
        for window in windows:
            grouped = df.groupby("season_year")[col]
            df[f"{col}_rollmean_{window}"] = grouped.transform(lambda x: x.rolling(window, min_periods=window).mean())
            df[f"{col}_rollmin_{window}"]  = grouped.transform(lambda x: x.rolling(window, min_periods=window).min())
            df[f"{col}_rollmax_{window}"]  = grouped.transform(lambda x: x.rolling(window, min_periods=window).max())
    return df

In [415]:
train_feat = add_rolling_features(train_clean_df, base_features, rolling_windows)
test_feat = add_rolling_features(test_clean_df, base_features, rolling_windows)

print("Rolling features added.")
print("Train shape:", train_feat.shape)
print("Test shape:", test_feat.shape)

Rolling features added.
Train shape: (2214, 125)
Test shape: (738, 124)

In [416]:
train_feat.head()

,date,5cm_soil_moist,mean_dew_point_temp,max_temp,sea_level_pressure,sst_cameroon_mean_temperature_deg_c,sst_cameroon_mean_temperature_uncertainty,sst_indian_ocean_mean_temperature_deg_c,sst_indian_ocean_mean_temperature_uncertainty,potential_water_deficit,2m_temp,u10,vapor_pressure_deficit,dryspell_warn_7d,year,month,season_year,5cm_soil_moist_rollmean_7,5cm_soil_moist_rollmin_7,5cm_soil_moist_rollmax_7,5cm_soil_moist_rollmean_14,5cm_soil_moist_rollmin_14,5cm_soil_moist_rollmax_14,5cm_soil_moist_rollmean_30,5cm_soil_moist_rollmin_30,5cm_soil_moist_rollmax_30,mean_dew_point_temp_rollmean_7,mean_dew_point_temp_rollmin_7,mean_dew_point_temp_rollmax_7,mean_dew_point_temp_rollmean_14,mean_dew_point_temp_rollmin_14,mean_dew_point_temp_rollmax_14,mean_dew_point_temp_rollmean_30,mean_dew_point_temp_rollmin_30,mean_dew_point_temp_rollmax_30,max_temp_rollmean_7,max_temp_rollmin_7,max_temp_rollmax_7,max_temp_rollmean_14,max_temp_rollmin_14,max_temp_rollmax_14,max_temp_rollmean_30,max_temp_rollmin_30,max_temp_rollmax_30,sea_level_pressure_rollmean_7,sea_level_pressure_rollmin_7,sea_level_pressure_rollmax_7,sea_level_pressure_rollmean_14,sea_level_pressure_rollmin_14,sea_level_pressure_rollmax_14,sea_level_pressure_rollmean_30,sea_level_pressure_rollmin_30,sea_level_pressure_rollmax_30,sst_cameroon_mean_temperature_deg_c_rollmean_7,sst_cameroon_mean_temperature_deg_c_rollmin_7,sst_cameroon_mean_temperature_deg_c_rollmax_7,sst_cameroon_mean_temperature_deg_c_rollmean_14,sst_cameroon_mean_temperature_deg_c_rollmin_14,sst_cameroon_mean_temperature_deg_c_rollmax_14,sst_cameroon_mean_temperature_deg_c_rollmean_30,sst_cameroon_mean_temperature_deg_c_rollmin_30,sst_cameroon_mean_temperature_deg_c_rollmax_30,sst_cameroon_mean_temperature_uncertainty_rollmean_7,sst_cameroon_mean_temperature_uncertainty_rollmin_7,sst_cameroon_mean_temperature_uncertainty_rollmax_7,sst_cameroon_mean_temperature_uncertainty_rollmean_14,sst_cameroon_mean_temperature_uncertainty_rollmin_14,sst_cameroon_mean_temperature_uncertainty_rollmax_14,sst_cameroon_mean_temperature_uncertainty_rollmean_30,sst_cameroon_mean_temperature_uncertainty_rollmin_30,sst_cameroon_mean_temperature_uncertainty_rollmax_30,sst_indian_ocean_mean_temperature_deg_c_rollmean_7,sst_indian_ocean_mean_temperature_deg_c_rollmin_7,sst_indian_ocean_mean_temperature_deg_c_rollmax_7,sst_indian_ocean_mean_temperature_deg_c_rollmean_14,sst_indian_ocean_mean_temperature_deg_c_rollmin_14,sst_indian_ocean_mean_temperature_deg_c_rollmax_14,sst_indian_ocean_mean_temperature_deg_c_rollmean_30,sst_indian_ocean_mean_temperature_deg_c_rollmin_30,sst_indian_ocean_mean_temperature_deg_c_rollmax_30,sst_indian_ocean_mean_temperature_uncertainty_rollmean_7,sst_indian_ocean_mean_temperature_uncertainty_rollmin_7,sst_indian_ocean_mean_temperature_uncertainty_rollmax_7,sst_indian_ocean_mean_temperature_uncertainty_rollmean_14,sst_indian_ocean_mean_temperature_uncertainty_rollmin_14,sst_indian_ocean_mean_temperature_uncertainty_rollmax_14,sst_indian_ocean_mean_temperature_uncertainty_rollmean_30,sst_indian_ocean_mean_temperature_uncertainty_rollmin_30,sst_indian_ocean_mean_temperature_uncertainty_rollmax_30,potential_water_deficit_rollmean_7,potential_water_deficit_rollmin_7,potential_water_deficit_rollmax_7,potential_water_deficit_rollmean_14,potential_water_deficit_rollmin_14,potential_water_deficit_rollmax_14,potential_water_deficit_rollmean_30,potential_water_deficit_rollmin_30,potential_water_deficit_rollmax_30,2m_temp_rollmean_7,2m_temp_rollmin_7,2m_temp_rollmax_7,2m_temp_rollmean_14,2m_temp_rollmin_14,2m_temp_rollmax_14,2m_temp_rollmean_30,2m_temp_rollmin_30,2m_temp_rollmax_30,u10_rollmean_7,u10_rollmin_7,u10_rollmax_7,u10_rollmean_14,u10_rollmin_14,u10_rollmax_14,u10_rollmean_30,u10_rollmin_30,u10_rollmax_30,vapor_pressure_deficit_rollmean_7,vapor_pressure_deficit_rollmin_7,vapor_pressure_deficit_rollmax_7,vapor_pressure_deficit_rollmean_14,vapor_pressure_deficit_rollmin_14,vapor_pressure_deficit_rollmax_14,vapor_pressure_deficit_rollmean_30,vapor_pressure_deficit_rollmin_30,vapor_pressure_deficit_rollmax_30
0,2002-07-01,0.14,16.31,40.13,101.01,26.06,0.19,28.84,0.12,-4.61,32.73,0.76,5.45,0,2002,7,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2002-07-02,0.14,16.77,41.36,100.81,26.10,0.19,28.85,0.12,-2.92,33.37,0.68,5.52,0,2002,7,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2002-07-03,0.14,19.72,38.05,100.97,26.11,0.20,28.82,0.12,7.59,31.57,1.41,4.23,0,2002,7,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2002-07-04,0.14,18.50,39.51,100.94,26.14,0.23,28.79,0.12,-2.29,32.59,1.49,4.68,0,2002,7,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2002-07-05,0.14,17.68,40.47,100.86,26.29,0.21,28.78,0.12,-2.87,33.59,1.07,5.15,0,2002,7,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [417]:
# Define key signals for lag features
lag_features = [
    "vapor_pressure_deficit",
    "5cm_soil_moist",
    "max_temp",
    "mean_dew_point_temp",
    "u10",
    "sea_level_pressure",
    "potential_water_deficit",
    "sst_cameroon_mean_temperature_deg_c",
    "sst_indian_ocean_mean_temperature_deg_c",
]
# Keep only columns that actually exist in the dataframe
lag_features = [col for col in lag_features if col in train_feat.columns]

print("Lag feature columns found:")
print(lag_features)

Lag feature columns found:
['vapor_pressure_deficit', '5cm_soil_moist', 'max_temp', 'mean_dew_point_temp', 'u10', 'sea_level_pressure', 'potential_water_deficit', 'sst_cameroon_mean_temperature_deg_c', 'sst_indian_ocean_mean_temperature_deg_c']

In [418]:
# Create lag features and diff_1 / diff_7
lags = [1, 7, 14]

def add_lag_features(df, feature_cols, lags):
    df = df.copy()
    
    for col in feature_cols:
        grouped = df.groupby("season_year")[col]
        
        for lag in lags:
            df[f"{col}_lag_{lag}"] = grouped.transform(lambda x: x.shift(lag))
        
        # Short-term change: today minus yesterday
        if 1 in lags:
            df[f"{col}_diff_1"] = df[col] - df[f"{col}_lag_1"]
        
        # Trend proxy: today minus 7 days ago
        if 7 in lags:
            df[f"{col}_diff_7"] = df[col] - df[f"{col}_lag_7"]
    
    return df


train_feat = add_lag_features(train_feat, lag_features, lags)
test_feat = add_lag_features(test_feat, lag_features, lags)

print("Lag and diff features added.")
print("Train shape:", train_feat.shape)
print("Test shape:", test_feat.shape)

Lag and diff features added.
Train shape: (2214, 170)
Test shape: (738, 169)

In [419]:
 # Drop early-season rows with incomplete rolling/lag features

# Since rolling window max = 30, the first 29 rows of each season
# will not have full rolling statistics.
# We drop rows with any NA in engineered numeric columns.

def drop_engineering_na(df):
    df = df.copy()
    return df.dropna().reset_index(drop=True)

train_feat = drop_engineering_na(train_feat)
test_feat = drop_engineering_na(test_feat)

print("After dropping NA rows:")
print("Train shape:", train_feat.shape)
print("Test shape:", test_feat.shape)

After dropping NA rows:
Train shape: (1692, 170)
Test shape: (470, 169)

In [420]:
train_feat.head()

,date,5cm_soil_moist,mean_dew_point_temp,max_temp,sea_level_pressure,sst_cameroon_mean_temperature_deg_c,sst_cameroon_mean_temperature_uncertainty,sst_indian_ocean_mean_temperature_deg_c,sst_indian_ocean_mean_temperature_uncertainty,potential_water_deficit,2m_temp,u10,vapor_pressure_deficit,dryspell_warn_7d,year,month,season_year,5cm_soil_moist_rollmean_7,5cm_soil_moist_rollmin_7,5cm_soil_moist_rollmax_7,5cm_soil_moist_rollmean_14,5cm_soil_moist_rollmin_14,5cm_soil_moist_rollmax_14,5cm_soil_moist_rollmean_30,5cm_soil_moist_rollmin_30,5cm_soil_moist_rollmax_30,mean_dew_point_temp_rollmean_7,mean_dew_point_temp_rollmin_7,mean_dew_point_temp_rollmax_7,mean_dew_point_temp_rollmean_14,mean_dew_point_temp_rollmin_14,mean_dew_point_temp_rollmax_14,mean_dew_point_temp_rollmean_30,mean_dew_point_temp_rollmin_30,mean_dew_point_temp_rollmax_30,max_temp_rollmean_7,max_temp_rollmin_7,max_temp_rollmax_7,max_temp_rollmean_14,max_temp_rollmin_14,max_temp_rollmax_14,max_temp_rollmean_30,max_temp_rollmin_30,max_temp_rollmax_30,sea_level_pressure_rollmean_7,sea_level_pressure_rollmin_7,sea_level_pressure_rollmax_7,sea_level_pressure_rollmean_14,sea_level_pressure_rollmin_14,sea_level_pressure_rollmax_14,sea_level_pressure_rollmean_30,sea_level_pressure_rollmin_30,sea_level_pressure_rollmax_30,sst_cameroon_mean_temperature_deg_c_rollmean_7,sst_cameroon_mean_temperature_deg_c_rollmin_7,sst_cameroon_mean_temperature_deg_c_rollmax_7,sst_cameroon_mean_temperature_deg_c_rollmean_14,sst_cameroon_mean_temperature_deg_c_rollmin_14,sst_cameroon_mean_temperature_deg_c_rollmax_14,sst_cameroon_mean_temperature_deg_c_rollmean_30,sst_cameroon_mean_temperature_deg_c_rollmin_30,sst_cameroon_mean_temperature_deg_c_rollmax_30,sst_cameroon_mean_temperature_uncertainty_rollmean_7,sst_cameroon_mean_temperature_uncertainty_rollmin_7,sst_cameroon_mean_temperature_uncertainty_rollmax_7,sst_cameroon_mean_temperature_uncertainty_rollmean_14,sst_cameroon_mean_temperature_uncertainty_rollmin_14,sst_cameroon_mean_temperature_uncertainty_rollmax_14,sst_cameroon_mean_temperature_uncertainty_rollmean_30,sst_cameroon_mean_temperature_uncertainty_rollmin_30,sst_cameroon_mean_temperature_uncertainty_rollmax_30,sst_indian_ocean_mean_temperature_deg_c_rollmean_7,sst_indian_ocean_mean_temperature_deg_c_rollmin_7,sst_indian_ocean_mean_temperature_deg_c_rollmax_7,sst_indian_ocean_mean_temperature_deg_c_rollmean_14,sst_indian_ocean_mean_temperature_deg_c_rollmin_14,sst_indian_ocean_mean_temperature_deg_c_rollmax_14,sst_indian_ocean_mean_temperature_deg_c_rollmean_30,sst_indian_ocean_mean_temperature_deg_c_rollmin_30,sst_indian_ocean_mean_temperature_deg_c_rollmax_30,sst_indian_ocean_mean_temperature_uncertainty_rollmean_7,sst_indian_ocean_mean_temperature_uncertainty_rollmin_7,sst_indian_ocean_mean_temperature_uncertainty_rollmax_7,sst_indian_ocean_mean_temperature_uncertainty_rollmean_14,sst_indian_ocean_mean_temperature_uncertainty_rollmin_14,sst_indian_ocean_mean_temperature_uncertainty_rollmax_14,sst_indian_ocean_mean_temperature_uncertainty_rollmean_30,sst_indian_ocean_mean_temperature_uncertainty_rollmin_30,sst_indian_ocean_mean_temperature_uncertainty_rollmax_30,potential_water_deficit_rollmean_7,potential_water_deficit_rollmin_7,potential_water_deficit_rollmax_7,potential_water_deficit_rollmean_14,potential_water_deficit_rollmin_14,potential_water_deficit_rollmax_14,potential_water_deficit_rollmean_30,potential_water_deficit_rollmin_30,potential_water_deficit_rollmax_30,2m_temp_rollmean_7,2m_temp_rollmin_7,2m_temp_rollmax_7,2m_temp_rollmean_14,2m_temp_rollmin_14,2m_temp_rollmax_14,2m_temp_rollmean_30,2m_temp_rollmin_30,2m_temp_rollmax_30,u10_rollmean_7,u10_rollmin_7,u10_rollmax_7,u10_rollmean_14,u10_rollmin_14,u10_rollmax_14,u10_rollmean_30,u10_rollmin_30,u10_rollmax_30,vapor_pressure_deficit_rollmean_7,vapor_pressure_deficit_rollmin_7,vapor_pressure_deficit_rollmax_7,vapor_pressure_deficit_rollmean_14,vapor_pressure_deficit_rollmin_14,vapor_pressure_deficit_rollmax_14,vapor_pressure_deficit_rollmean_30,vapor_pressure_deficit_rollmin_30,vapor_pressure_deficit_rollmax_30,vapor_pressure_deficit_lag_1,vapor_pressure_deficit_lag_7,vapor_pressure_deficit_lag_14,vapor_pressure_deficit_diff_1,vapor_pressure_deficit_diff_7,5cm_soil_moist_lag_1,5cm_soil_moist_lag_7,5cm_soil_moist_lag_14,5cm_soil_moist_diff_1,5cm_soil_moist_diff_7,max_temp_lag_1,max_temp_lag_7,max_temp_lag_14,max_temp_diff_1,max_temp_diff_7,mean_dew_point_temp_lag_1,mean_dew_point_temp_lag_7,mean_dew_point_temp_lag_14,mean_dew_point_temp_diff_1,mean_dew_point_temp_diff_7,u10_lag_1,u10_lag_7,u10_lag_14,u10_diff_1,u10_diff_7,sea_level_pressure_lag_1,sea_level_pressure_lag_7,sea_level_pressure_lag_14,sea_level_pressure_diff_1,sea_level_pressure_diff_7,potential_water_deficit_lag_1,potential_water_deficit_lag_7,potential_water_deficit_lag_14,potential_water_deficit_diff_1,potential_water_deficit_diff_7,sst_cameroon_mean_temperature_deg_c_lag_1,sst_cameroon_mean_temperature_deg_c_lag_7,sst_cameroon_mean_temperature_deg_c_lag_14,sst_cameroon_mean_temperature_deg_c_diff_1,sst_cameroon_mean_temperature_deg_c_diff_7,sst_indian_ocean_mean_temperature_deg_c_lag_1,sst_indian_ocean_mean_temperature_deg_c_lag_7,sst_indian_ocean_mean_temperature_deg_c_lag_14,sst_indian_ocean_mean_temperature_deg_c_diff_1,sst_indian_ocean_mean_temperature_deg_c_diff_7
0,2002-07-30,0.26,21.19,32.71,101.03,25.48,0.23,28.10,0.16,2.48,26.74,-0.70,2.79,0,2002,7,2002,0.24,0.20,0.28,0.23,0.19,0.28,0.20,0.13,0.28,20.93,19.86,21.62,20.98,19.86,21.88,19.52,16.01,21.88,32.58,31.19,34.09,33.43,31.19,35.75,35.74,31.19,41.36,101.21,101.03,101.34,101.10,100.88,101.34,101.02,100.77,101.34,25.44,25.34,25.48,25.38,25.15,25.51,25.61,25.15,26.29,0.23,0.22,0.26,0.23,0.22,0.26,0.22,0.19,0.26,28.02,27.90,28.17,28.16,27.9,28.40,28.43,27.9,28.85,0.13,0.12,0.16,0.13,0.12,0.16,0.13,0.12,0.16,2.98,-3.11,8.11,1.26,-3.85,8.11,-2.93e-01,-4.61,8.11,27.01,26.31,27.84,27.60,26.31,29.11,29.39,26.31,33.59,0.09,-0.7,1.42,-6.27e-02,-1.45,1.42,0.48,-1.45,2.27,2.80,2.29,3.01,2.98,2.29,3.55,3.71,2.29,5.52,2.71,3.06,4.33,0.08,-0.27,0.25,0.21,0.24,2.20e-03,0.04,32.30,33.97,38.65,0.41,-1.25,21.62,21.35,19.42,-0.44,-0.16,0.86,-0.39,0.29,-1.56,-0.31,101.32,101.07,100.94,-0.30,-0.05,1.53,-1.54,-3.79,0.95,4.02,25.47,25.29,25.53,9.28e-03,1.92e-01,27.98,28.17,28.57,1.22e-01,-0.06
1,2002-07-31,0.22,19.07,32.39,100.99,25.48,0.24,27.98,0.15,2.68,27.04,0.44,2.94,0,2002,7,2002,0.24,0.20,0.28,0.23,0.19,0.28,0.20,0.13,0.28,20.64,19.07,21.62,20.88,19.07,21.88,19.62,16.01,21.88,32.47,31.19,34.09,33.39,31.19,35.75,35.48,31.19,41.36,101.19,100.99,101.34,101.10,100.88,101.34,101.02,100.77,101.34,25.46,25.41,25.48,25.37,25.15,25.48,25.59,25.15,26.29,0.23,0.22,0.24,0.23,0.22,0.26,0.22,0.19,0.26,28.00,27.90,28.17,28.14,27.9,28.34,28.40,27.9,28.85,0.14,0.12,0.16,0.13,0.12,0.16,0.13,0.12,0.16,2.54,-3.11,8.11,1.22,-3.85,8.11,-5.05e-02,-4.60,8.11,26.93,26.31,27.84,27.57,26.31,29.11,29.20,26.31,33.59,0.23,-0.7,1.42,5.71e-02,-1.45,1.42,0.47,-1.45,2.27,2.79,2.29,3.00,2.97,2.29,3.55,3.62,2.29,5.52,2.79,3.01,3.09,0.16,-0.06,0.26,0.21,0.20,-4.13e-02,0.01,32.71,33.16,32.94,-0.33,-0.78,21.19,21.14,20.42,-2.12,-2.07,-0.70,-0.54,-1.24,1.14,0.97,101.03,101.10,100.96,-0.04,-0.11,2.48,5.72,3.18,0.20,-3.04,25.48,25.34,25.51,1.68e-03,1.36e-01,28.10,28.12,28.40,-1.19e-01,-0.14
2,2002-08-01,0.22,20.12,35.32,101.00,25.41,0.23,27.99,0.12,-3.47,28.20,-0.31,3.44,0,2002,8,2002,0.24,0.22,0.28,0.23,0.19,0.28,0.20,0.13,0.28,20.68,19.07,21.62,20.84,19.07,21.88,19.73,16.01,21.88,32.92,31.19,35.32,33.42,31.19,35.75,35.28,31.19,40.47,101.16,100.99,101.34,101.10,100.88,101.34,101.03,100.77,101.34,25.46,25.41,25.48,25.37,25.15,25.48,25.57,25.15,26.29,0.23,0.22,0.24,0.23,0.22,0.26,0.22,0.20,0.26,27.98,27.90,28.10,28.11,27.9,28.33,28.37,27.9,28.82,0.13,0.12,0.16,0.13,0.12,0.16,0.13,0.12,0.16,1.19,-3.47,8.11,0.70,-3.85,8.11,-6.90e-02,-4.60,8.11,27.07,26.31,28.20,27.60,26.31,29.11,29.03,26.31,33.59,0.15,-0.7,1.42,-3.28e-02,-1.45,1.42,0.44,-1.45,2.27,2.88,2.29,3.44,2.98,2.29,3.55,3.55,2.29,5.15,2.94,2.85,3.28,0.50,0.59,0.22,0.20,0.21,3.40e-03,0.02,32.39,32.16,34.88,2.93,3.16,19.07,19.86,20.74,1.05,0.26,0.44,0.26,0.95,-0.75,-0.57,100.99,101.18,101.02,0.01,-0.19,2.68,6.02,3.81,-6.16,-9.50,25.48,25.41,25.41,-6.71e-02,6.57e-03,27.98,28.17,28.34,9.60e-03,-0.17
3,2002-08-02,0.25,20.61,32.69,101.16,25.34,0.31,27.96,0.12,1.43,26.81,0.74,2.69,0,2002,8,2002,0.24,0.22,0.26,0.24,0.20,0.28,0.21,0.13,0.28,20.73,19.07,21.62,20.84,19.07,21.88,19.76,16.01,21.88,32.96,31.19,35.32,33.42,31.19,35.75,35.10,31.19,40.47,101.14,100.99,101.34,101.10,100.88,101.34,101.03,100.77,101.34,25.45,25.34,25.48,25.37,25.15,25.48,25.54,25.15,26.29,0.24,0.22,0.31,0.24,0.22,0.31,0.23,0.20,0.31,27.98,27.90,28.10,28.08,27.9,28.32,28.34,27.9,28.79,0.13,0.12,0.16,0.13,0.12,0.16,0.13,0.12,0.16,1.38,-3.47,8.11,1.06,-3.85,8.11,-2.75e-01,-4.60,8.11,27.05,26.31,28.20,27.55,26.31,29.11,28.87,26.31,33.59,0.28,-0.7,1.42,1.16e-03,-1.45,1.42,0.41,-1.45,2.27,2.84,2.29,3.44,2.98,2.29,3.55,3.50,2.29,5.15,3.44,2.96,2.65,-0.75,-0.27,0.22,0.28,0.19,3.42e-02,-0.03,35.32,32.42,32.67,-2.63,0.27,20.12,20.25,20.48,0.49,0.36,-0.31,-0.15,0.27,1.05,0.89,101.00,101.29,101.11,0.16,-0.14,-3.47,0.08,-3.55,4.90,1.34,25.41,25.45,25.32,-7.21e-02,-1.04e-01,27.99,27.97,28.33,-3.64e-02,-0.02
4,2002-08-03,0.27,19.49,33.63,101.06,25.15,0.31,27.98,0.12,5.78,27.25,0.56,3.16,0,2002,8,2002,0.24,0.22,0.27,0.24,0.20,0.28,0.21,0.13,0.28,20.45,19.07,21.62,20.72,19.07,21.88,19.79,16.01,21.88,32.89,31.19,35.32,33.28,31.19,35.75,34.91,31.19,40.47,101.13,100.99,101.34,101.11,100.88,101.34,101.04,100.77,101.34,25.40,25.15,25.48,25.37,25.15,25.48,25.51,25.15,26.29,0.25,0.22,0.31,0.25,0.22,0.31,0.23,0.20,0.31,27.99,27.93,28.10,28.06,27.9,28.32,28.31,27.9,28.78,0.13,0.12,0.16,0.13,0.12,0.16,0.13,0.12,0.16,1.04,-3.47,5.78,1.58,-3.85,8.11,-5.42e-03,-4.60,8.11,26.97,26.31,28.20,27.42,26.31,29.08,28.69,26.31,33.59,0.43,-0.7,1.42,6.52e-02,-1.45,1.42,0.38,-1.45,2.27,2.86,2.29,3.44,2.97,2.29,3.55,3.45,2.29,5.15,2.69,3.00,3.30,0.47,0.16,0.25,0.25,0.26,2.12e-02,0.03,32.69,34.09,35.64,0.94,-0.46,20.61,21.42,21.17,-1.12,-1.93,0.74,-0.50,-0.34,-0.19,1.06,101.16,101.17,100.94,-0.10,-0.11,1.43,8.11,-1.53,4.35,-2.33,25.34,25.48,25.23,-1.89e-01,-3.31e-01,27.96,27.90,28.32,2.63e-02,0.08

In [421]:
train_feat.to_csv("../data/processed/train_features.csv", index=False)
test_feat.to_csv("../data/processed/test_features.csv", index=False)

print("Feature-engineered datasets saved successfully.")

Feature-engineered datasets saved successfully.